GET http://localhost:3000

###

GET http://localhost:3000/devices

###

GET http://localhost:3000/device?id=1


###

POST http://localhost:3000/devices
Content-Type: application/json

{
  "id": "5",
  "name": "Mede temperatura sala 203",
  "unidade": "ºF",
  "naoera": "pra ir"
}

###

DELETE http://localhost:3000/device?id=1

###

PUT http://localhost:3000/devices
Content-Type: application/json

{
  "id": "4",
  "name": "Mede temperatura sala 203",
  "unidade": "ºF"
}